-- ==============================================================================
-- DỰ ÁN: ENGLISH CENTER CRM - PHẦN MỀM CRM QUẢN LÝ TUYỂN SINH VÀ ĐÀO TẠO
-- MÃ CÔNG VIỆC: DB-02 (Physical Database Schema & DDL Script)
-- TÁC GIẢ: Tam Minh (@tamminh6) - Database Engineer / Phân tích hệ thống
-- RDBMS MỤC TIÊU: PostgreSQL 14+ (Chuẩn ANSI SQL, Khóa chính Số nguyên INT tự tăng)
-- ==============================================================================

-- ==============================================================================
-- 1. DỌN DẸP DỮ LIỆU CŨ (DROP VIEWS, TRIGGERS & TABLES THEO THỨ TỰ PHỤ THUỘC)
-- ==============================================================================
DROP VIEW IF EXISTS v_sales_kpi_dashboard CASCADE;
DROP VIEW IF EXISTS v_leads_kanban CASCADE;
DROP VIEW IF EXISTS v_classes_summary CASCADE;

DROP TABLE IF EXISTS payment_receipts CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS placement_tests CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS interaction_logs CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS sync_class_enrolled_count() CASCADE;

-- ==============================================================================
-- 2. ĐỊNH NGHĨA CÁC HÀM XỬ LÝ (TRIGGER FUNCTIONS)
-- ==============================================================================

-- Hàm tự động cập nhật trường updated_at mỗi khi có thao tác UPDATE
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Hàm tự động tính toán sĩ số thực tế (current_enrolled) & tự khóa lớp (status = 'FULL')
CREATE OR REPLACE FUNCTION sync_class_enrolled_count()
RETURNS TRIGGER AS $$
DECLARE
    target_class_id INT;
    actual_count INT;
    class_capacity INT;
BEGIN
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        target_class_id := NEW.class_id;
    ELSE
        target_class_id := OLD.class_id;
    END IF;

    -- Đếm sĩ số học viên thực tế đang học
    SELECT COUNT(*) INTO actual_count
    FROM enrollments
    WHERE class_id = target_class_id AND status = 'ENROLLED';

    -- Lấy sức chứa tối đa của lớp
    SELECT max_capacity INTO class_capacity
    FROM classes
    WHERE id = target_class_id;

    -- Cập nhật sĩ số vào bảng classes
    UPDATE classes
    SET current_enrolled = actual_count,
        status = CASE 
            WHEN actual_count >= class_capacity THEN 'FULL'
            WHEN status = 'FULL' AND actual_count < class_capacity THEN 'OPEN'
            ELSE status
        END,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = target_class_id;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ==============================================================================
-- 3. KHỞI TẠO CÁC BẢNG DỮ LIỆU CỐT LÕI (10 TABLES - CHUẨN 3NF - ID SỐ NGUYÊN GỌN)
-- ==============================================================================

-- 3.1. Bảng roles (Danh mục Vai trò Người dùng - RBAC)
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(30) UNIQUE NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_role_code CHECK (role_code IN ('ADMIN', 'SALES', 'ACADEMIC'))
);

CREATE TRIGGER trg_roles_updated_at 
BEFORE UPDATE ON roles 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.2. Bảng users (Tài khoản Nhân sự Trung tâm)
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    phone_number VARCHAR(20),
    role_id INT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    avatar_url VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_username_format CHECK (username ~ '^[a-zA-Z0-9_\.]+$')
);

CREATE TRIGGER trg_users_updated_at 
BEFORE UPDATE ON users 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.3. Bảng leads (Khách hàng Tiềm năng & Phễu Tuyển sinh)
CREATE TABLE leads (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(120),
    interest VARCHAR(50) NOT NULL,
    source_channel VARCHAR(50) NOT NULL,
    pipeline_stage VARCHAR(30) NOT NULL DEFAULT 'NEW',
    lost_reason VARCHAR(100),
    assigned_sales_id INT REFERENCES users(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_leads_interest CHECK (interest IN ('IELTS', 'TOEIC', 'COMMUNICATION')),
    CONSTRAINT chk_leads_source CHECK (source_channel IN ('FB_ADS', 'WEBSITE', 'HOTLINE', 'WALK_IN', 'REFERRAL')),
    CONSTRAINT chk_leads_stage CHECK (pipeline_stage IN ('NEW', 'CONTACTING', 'TEST_SCHEDULED', 'ENROLLED', 'LOST'))
);

CREATE TRIGGER trg_leads_updated_at 
BEFORE UPDATE ON leads 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.4. Bảng interaction_logs (Nhật ký Tương tác & Lịch sử Chăm sóc Lead)
CREATE TABLE interaction_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    interaction_type VARCHAR(30) NOT NULL,
    potential_level VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    next_follow_up_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_interaction_type CHECK (interaction_type IN ('PHONE_CALL', 'SMS', 'DIRECT_MEETING', 'SYSTEM_NOTE')),
    CONSTRAINT chk_potential_level CHECK (potential_level IN ('HOT', 'WARM', 'COLD'))
);

-- 3.5. Bảng courses (Danh mục Khóa học Đào tạo)
CREATE TABLE courses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(30) UNIQUE NOT NULL,
    course_name VARCHAR(100) NOT NULL,
    total_lessons INTEGER NOT NULL CHECK (total_lessons > 0),
    standard_tuition NUMERIC(12,2) NOT NULL CHECK (standard_tuition >= 0),
    min_entry_score NUMERIC(3,1) CHECK (min_entry_score >= 0.0 AND min_entry_score <= 9.0),
    max_entry_score NUMERIC(3,1) CHECK (max_entry_score >= 0.0 AND max_entry_score <= 9.0),
    target_output VARCHAR(100),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_courses_updated_at 
BEFORE UPDATE ON courses 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.6. Bảng placement_tests (Lịch hẹn & Kết quả Đánh giá Trình độ Đầu vào)
CREATE TABLE placement_tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id INT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    test_date DATE NOT NULL,
    time_slot VARCHAR(20) NOT NULL,
    room VARCHAR(50),
    test_type VARCHAR(30) NOT NULL,
    attendance_status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    listening_score NUMERIC(3,1) CHECK (listening_score IS NULL OR (listening_score >= 0.0 AND listening_score <= 9.0)),
    reading_score NUMERIC(3,1) CHECK (reading_score IS NULL OR (reading_score >= 0.0 AND reading_score <= 9.0)),
    writing_score NUMERIC(3,1) CHECK (writing_score IS NULL OR (writing_score >= 0.0 AND writing_score <= 9.0)),
    speaking_score NUMERIC(3,1) CHECK (speaking_score IS NULL OR (speaking_score >= 0.0 AND speaking_score <= 9.0)),
    overall_score NUMERIC(3,1) CHECK (overall_score IS NULL OR (overall_score >= 0.0 AND overall_score <= 9.0)),
    suggested_course_id INT REFERENCES courses(id) ON DELETE SET NULL,
    examiner_feedback TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_test_type CHECK (test_type IN ('IELTS', 'TOEIC', 'GENERAL')),
    CONSTRAINT chk_attendance_status CHECK (attendance_status IN ('SCHEDULED', 'PRESENT', 'ABSENT', 'CANCELLED'))
);

CREATE TRIGGER trg_placement_tests_updated_at 
BEFORE UPDATE ON placement_tests 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.7. Bảng classes (Danh sách Lớp học Mở mới)
CREATE TABLE classes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    class_code VARCHAR(50) UNIQUE NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    schedule_days VARCHAR(30) NOT NULL,
    time_slot VARCHAR(30) NOT NULL,
    room VARCHAR(50),
    teacher_name VARCHAR(100),
    start_date DATE NOT NULL,
    max_capacity INTEGER NOT NULL DEFAULT 15 CHECK (max_capacity > 0),
    current_enrolled INTEGER NOT NULL DEFAULT 0 CHECK (current_enrolled >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_class_schedule_days CHECK (schedule_days IN ('MON_WED_FRI', 'TUE_THU_SAT', 'WEEKEND')),
    CONSTRAINT chk_class_status CHECK (status IN ('PLANNING', 'OPEN', 'FULL', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TRIGGER trg_classes_updated_at 
BEFORE UPDATE ON classes 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.8. Bảng students (Hồ sơ Học viên Chính thức)
CREATE TABLE students (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(30) UNIQUE NOT NULL,
    lead_id INT UNIQUE REFERENCES leads(id) ON DELETE SET NULL,
    full_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(120),
    date_of_birth DATE,
    address VARCHAR(255),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_students_updated_at 
BEFORE UPDATE ON students 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3.9. Bảng enrollments (Hồ sơ Ghi danh & Xếp lớp Học viên)
CREATE TABLE enrollments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE RESTRICT,
    consultant_id INT REFERENCES users(id) ON DELETE SET NULL,
    enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    original_tuition NUMERIC(12,2) NOT NULL CHECK (original_tuition >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0.00 CHECK (discount_amount >= 0),
    final_amount NUMERIC(12,2) NOT NULL CHECK (final_amount >= 0),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    status VARCHAR(20) NOT NULL DEFAULT 'ENROLLED',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_student_class UNIQUE(student_id, class_id),
    CONSTRAINT chk_enrollment_payment_status CHECK (payment_status IN ('UNPAID', 'PARTIAL', 'FULLY_PAID')),
    CONSTRAINT chk_enrollment_status CHECK (status IN ('ENROLLED', 'TRANSFERRED', 'DROPPED', 'COMPLETED'))
);

CREATE TRIGGER trg_enrollments_updated_at 
BEFORE UPDATE ON enrollments 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Kích hoạt trigger tự động đồng bộ sĩ số lớp khi ghi danh thay đổi
CREATE TRIGGER trg_sync_class_enrolled
AFTER INSERT OR UPDATE OR DELETE ON enrollments
FOR EACH ROW EXECUTE FUNCTION sync_class_enrolled_count();

-- 3.10. Bảng payment_receipts (Biên lai Thu Tiền Học phí)
CREATE TABLE payment_receipts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id INT NOT NULL REFERENCES enrollments(id) ON DELETE RESTRICT,
    receipt_code VARCHAR(50) UNIQUE NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(30) NOT NULL DEFAULT 'BANK_TRANSFER',
    transaction_reference VARCHAR(100),
    receiver_id INT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    CONSTRAINT chk_payment_method CHECK (payment_method IN ('CASH', 'BANK_TRANSFER'))
);

-- ==============================================================================
-- 4. BỘ CHỈ MỤC TỐI ƯU HIỆU NĂNG TRUY VẤN (PERFORMANCE INDEXES)
-- ==============================================================================
CREATE INDEX idx_leads_phone ON leads(phone_number);
CREATE INDEX idx_leads_stage_assigned ON leads(pipeline_stage, assigned_sales_id);
CREATE INDEX idx_leads_created_at ON leads(created_at DESC);

CREATE INDEX idx_interaction_logs_lead ON interaction_logs(lead_id, created_at DESC);

CREATE INDEX idx_placement_tests_schedule ON placement_tests(test_date, time_slot, room);
CREATE INDEX idx_placement_tests_lead ON placement_tests(lead_id);

CREATE INDEX idx_classes_course ON classes(course_id);
CREATE INDEX idx_classes_status ON classes(status);
CREATE INDEX idx_classes_start_date ON classes(start_date);

CREATE INDEX idx_students_phone ON students(phone_number);
CREATE INDEX idx_students_lead ON students(lead_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_class ON enrollments(class_id);
CREATE INDEX idx_enrollments_consultant ON enrollments(consultant_id);

CREATE INDEX idx_payment_receipts_enrollment ON payment_receipts(enrollment_id);
CREATE INDEX idx_payment_receipts_paid_at ON payment_receipts(paid_at DESC);

-- ==============================================================================
-- 5. CÁC DATABASE VIEWS HỖ TRỢ BÁO CÁO & FRONTEND DASHBOARD
-- ==============================================================================
CREATE OR REPLACE VIEW v_classes_summary AS
SELECT 
    c.id AS class_id,
    c.class_code,
    c.class_name,
    co.course_name,
    c.schedule_days,
    c.time_slot,
    c.room,
    c.teacher_name,
    c.start_date,
    c.max_capacity,
    c.current_enrolled,
    (c.max_capacity - c.current_enrolled) AS remaining_slots,
    ROUND((c.current_enrolled::NUMERIC / c.max_capacity::NUMERIC) * 100, 1) AS occupancy_rate,
    c.status
FROM classes c
JOIN courses co ON c.course_id = co.id;

CREATE OR REPLACE VIEW v_leads_kanban AS
SELECT 
    l.id AS lead_id,
    l.full_name,
    l.phone_number,
    l.email,
    l.interest,
    l.source_channel,
    l.pipeline_stage,
    l.lost_reason,
    u.full_name AS assigned_sales_name,
    l.created_at,
    (SELECT MAX(created_at) FROM interaction_logs WHERE lead_id = l.id) AS last_contacted_at,
    (SELECT COUNT(*) FROM interaction_logs WHERE lead_id = l.id) AS total_interactions
FROM leads l
LEFT JOIN users u ON l.assigned_sales_id = u.id;

CREATE OR REPLACE VIEW v_sales_kpi_dashboard AS
SELECT 
    u.id AS sales_id,
    u.full_name AS sales_name,
    COUNT(DISTINCT l.id) AS total_assigned_leads,
    COUNT(DISTINCT CASE WHEN l.pipeline_stage = 'ENROLLED' THEN l.id END) AS converted_students,
    ROUND(
        CASE 
            WHEN COUNT(DISTINCT l.id) = 0 THEN 0 
            ELSE (COUNT(DISTINCT CASE WHEN l.pipeline_stage = 'ENROLLED' THEN l.id END)::NUMERIC / COUNT(DISTINCT l.id)::NUMERIC) * 100 
        END, 1
    ) AS conversion_rate,
    COALESCE(SUM(pr.amount), 0) AS total_revenue_collected
FROM users u
LEFT JOIN leads l ON u.id = l.assigned_sales_id
LEFT JOIN enrollments e ON u.id = e.consultant_id
LEFT JOIN payment_receipts pr ON e.id = pr.enrollment_id
JOIN roles r ON u.role_id = r.id
WHERE r.role_code = 'SALES'
GROUP BY u.id, u.full_name;
